name: screenshots ci actions
on: [push]
  
jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots-desktop-site
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://62967b0dfa90f33b6afb289a--spiffy-muffin-7b271a.netlify.app/
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-desktop-screenshots 
